
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "authentificationWS", targetNamespace = "http://service/", wsdlLocation = "http://192.168.1.12:8586/AuthentificationService?wsdl")
public class AuthentificationWS
    extends Service
{

    private final static URL AUTHENTIFICATIONWS_WSDL_LOCATION;
    private final static WebServiceException AUTHENTIFICATIONWS_EXCEPTION;
    private final static QName AUTHENTIFICATIONWS_QNAME = new QName("http://service/", "authentificationWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.12:8586/AuthentificationService?wsdl");
            // ADRESSE A MODIFIER EN FONCTION DE L'ADRESSE DE LA MACHINE
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTIFICATIONWS_WSDL_LOCATION = url;
        AUTHENTIFICATIONWS_EXCEPTION = e;
    }

    public AuthentificationWS() {
        super(__getWsdlLocation(), AUTHENTIFICATIONWS_QNAME);
    }

    public AuthentificationWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTIFICATIONWS_QNAME, features);
    }

    public AuthentificationWS(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTIFICATIONWS_QNAME);
    }

    public AuthentificationWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTIFICATIONWS_QNAME, features);
    }

    public AuthentificationWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthentificationWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthentificationService
     */
    @WebEndpoint(name = "AuthentificationServicePort")
    public AuthentificationService getAuthentificationServicePort() {
        return super.getPort(new QName("http://service/", "AuthentificationServicePort"), AuthentificationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthentificationService
     */
    @WebEndpoint(name = "AuthentificationServicePort")
    public AuthentificationService getAuthentificationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AuthentificationServicePort"), AuthentificationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTIFICATIONWS_EXCEPTION!= null) {
            throw AUTHENTIFICATIONWS_EXCEPTION;
        }
        return AUTHENTIFICATIONWS_WSDL_LOCATION;
    }

}
